name: CS_RUNNER

on:
  schedule:
    - cron: '0 0,5,10,15,20 * * *'
  workflow_dispatch:
    inputs:
      replicas:
        description: Number of runners
        required: false
        default: "10"

  repository_dispatch:
    types:
      - webhook
      - CS_RUNNER

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.CUSTOM_PAT }}"

  setup-token:
    name: Setup runner token
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get_token.outputs.token }}

    steps:
      - id: get_token
        env:
          GITHUB_TOKEN: "${{ secrets.CUSTOM_PAT }}"
        run: |
          TOKEN=$(node -pe 'JSON.parse(process.argv[1]).token' "$(curl -s -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/orgs/coderschool-platform/actions/runners/registration-token)")
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

  generate-job-strategy-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      job-strategy-matrix: ${{ steps.generate.outputs.job-strategy-matrix }}
    steps:
      - id: generate
        run: |
          JOB_STRATEGY_MATRIX=$(node -e "let r=[]; for(let i = 1; i <= (process.env.NUMBER_OF_JOBS || 10); i++) { r.push(i) }; console.log(JSON.stringify(r));")
          echo "job-strategy-matrix=$JOB_STRATEGY_MATRIX" >> $GITHUB_OUTPUT
          echo $JOB_STRATEGY_MATRIX
        env:
          NUMBER_OF_JOBS: ${{ github.event.inputs.replicas }}

  setup-runners:
    name: Serve runner
    runs-on: ubuntu-latest
    needs: ["cleanup-runs", "setup-token", "generate-job-strategy-matrix"]
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-job-strategy-matrix.outputs.job-strategy-matrix) }}
      max-parallel: 100
    steps:
      - name: Setup runner
        run: |
          mkdir actions-runner && cd actions-runner
          curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
          echo "9e883d210df8c6028aff475475a457d380353f9d01877d51cc01a17b2a91161d  actions-runner-linux-x64-2.317.0.tar.gz" | shasum -a 256 -c
          tar xzf ./actions-runner-linux-x64-2.317.0.tar.gz

          ./config.sh --url https://github.com/coderschool-platform --token ${{ needs.setup-token.outputs.token }} --name CS_RUNNER_${{ matrix.job }} --replace --labels "self-hosted"

      - name: Start runner
        continue-on-error: true
        run: |
          cd actions-runner
          ./run.sh
